/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRegisterRouteImport } from './routes/app/register'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppChatIndexRouteImport } from './routes/app/chat/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/app/register',
  path: '/app/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/app/chat/',
  path: '/app/chat/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/login' | '/app/register' | '/app/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/login' | '/app/register' | '/app/chat'
  id: '__root__' | '/' | '/app/login' | '/app/register' | '/app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/register': {
      id: '/app/register'
      path: '/app/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/app/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
