/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRegisterRouteImport } from './routes/app/register'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppForgotPasswordRouteImport } from './routes/app/forgot-password'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppChatIndexRouteImport } from './routes/app/chat/index'
import { Route as AppChatChatSessionIdRouteImport } from './routes/app/chat/$chatSessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/app/register',
  path: '/app/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/app/forgot-password',
  path: '/app/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/app/chat',
  path: '/app/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatChatSessionIdRoute = AppChatChatSessionIdRouteImport.update({
  id: '/$chatSessionId',
  path: '/$chatSessionId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/login': typeof AppLoginRoute
  '/app/profile': typeof AppProfileRoute
  '/app/register': typeof AppRegisterRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/chat/$chatSessionId': typeof AppChatChatSessionIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/login': typeof AppLoginRoute
  '/app/profile': typeof AppProfileRoute
  '/app/register': typeof AppRegisterRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/chat/$chatSessionId': typeof AppChatChatSessionIdRoute
  '/app/chat': typeof AppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/login': typeof AppLoginRoute
  '/app/profile': typeof AppProfileRoute
  '/app/register': typeof AppRegisterRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/chat/$chatSessionId': typeof AppChatChatSessionIdRoute
  '/app/chat/': typeof AppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/chat'
    | '/app/forgot-password'
    | '/app/login'
    | '/app/profile'
    | '/app/register'
    | '/app/settings'
    | '/app/chat/$chatSessionId'
    | '/app/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/forgot-password'
    | '/app/login'
    | '/app/profile'
    | '/app/register'
    | '/app/settings'
    | '/app/chat/$chatSessionId'
    | '/app/chat'
  id:
    | '__root__'
    | '/'
    | '/app/chat'
    | '/app/forgot-password'
    | '/app/login'
    | '/app/profile'
    | '/app/register'
    | '/app/settings'
    | '/app/chat/$chatSessionId'
    | '/app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppLoginRoute: typeof AppLoginRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/register': {
      id: '/app/register'
      path: '/app/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/forgot-password': {
      id: '/app/forgot-password'
      path: '/app/forgot-password'
      fullPath: '/app/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/app/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/app/chat/$chatSessionId': {
      id: '/app/chat/$chatSessionId'
      path: '/$chatSessionId'
      fullPath: '/app/chat/$chatSessionId'
      preLoaderRoute: typeof AppChatChatSessionIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatChatSessionIdRoute: typeof AppChatChatSessionIdRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatChatSessionIdRoute: AppChatChatSessionIdRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppLoginRoute: AppLoginRoute,
  AppProfileRoute: AppProfileRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppSettingsRoute: AppSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
