# Generated by Django 6.0.3 on 2026-03-20 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRefered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatmessage')),
            ],
        ),
    ]
