# Generated by Django 6.0.3 on 2026-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentrefered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
