# Generated by Django 6.0.3 on 2026-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_city_alter_user_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
